// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTDoc.Infrastructure.Data;

#nullable disable

namespace PTDoc.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("PTDoc.Core.Models.Addendum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClinicalNoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClinicalNoteId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CreatedUtc");

                    b.ToTable("Addendums");
                });

            modelBuilder.Entity("PTDoc.Core.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AppointmentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClinicalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId")
                        .HasFilter("ClinicId IS NOT NULL");

                    b.HasIndex("LastModifiedUtc");

                    b.HasIndex("PatientId");

                    b.HasIndex("StartTimeUtc");

                    b.HasIndex("ClinicalId", "StartTimeUtc");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("PTDoc.Core.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("EventType");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("UserId")
                        .HasFilter("UserId IS NOT NULL");

                    b.HasIndex("EntityType", "EntityId")
                        .HasFilter("EntityType IS NOT NULL AND EntityId IS NOT NULL");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PTDoc.Core.Models.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("PTDoc.Core.Models.ClinicalNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CoSignedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CoSignedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CptCodesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfService")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NoteType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresCoSign")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignatureHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SignedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SignedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ClinicId")
                        .HasFilter("ClinicId IS NOT NULL");

                    b.HasIndex("DateOfService");

                    b.HasIndex("LastModifiedUtc");

                    b.HasIndex("PatientId");

                    b.HasIndex("SignedUtc");

                    b.ToTable("ClinicalNotes");
                });

            modelBuilder.Entity("PTDoc.Core.Models.ExternalIdentityMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InternalEntityId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("TenantId")
                        .HasFilter("TenantId IS NOT NULL");

                    b.HasIndex("PrincipalType", "InternalEntityId");

                    b.HasIndex("Provider", "ExternalSubject")
                        .IsUnique();

                    b.ToTable("ExternalIdentityMappings");
                });

            modelBuilder.Entity("PTDoc.Core.Models.ExternalSystemMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSystemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InternalPatientId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InternalPatientId");

                    b.HasIndex("IsActive");

                    b.HasIndex("ExternalSystemName", "ExternalId")
                        .IsUnique();

                    b.ToTable("ExternalSystemMappings");
                });

            modelBuilder.Entity("PTDoc.Core.Models.IntakeForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Consents")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PainMapData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StructuredDataJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique();

                    b.HasIndex("ClinicId")
                        .HasFilter("ClinicId IS NOT NULL");

                    b.HasIndex("LastModifiedUtc");

                    b.HasIndex("PatientId");

                    b.ToTable("IntakeForms");
                });

            modelBuilder.Entity("PTDoc.Core.Models.LoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("UserId")
                        .HasFilter("UserId IS NOT NULL");

                    b.HasIndex("Username");

                    b.HasIndex("Success", "AttemptedAt");

                    b.ToTable("LoginAttempts");
                });

            modelBuilder.Entity("PTDoc.Core.Models.ObjectiveMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BodyPart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWNL")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("ObjectiveMetrics");
                });

            modelBuilder.Entity("PTDoc.Core.Models.OutcomeMeasureResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClinicianId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("TEXT");

                    b.Property<int>("MeasureType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("NoteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId")
                        .HasFilter("ClinicId IS NOT NULL");

                    b.HasIndex("DateRecorded");

                    b.HasIndex("NoteId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientId", "MeasureType");

                    b.ToTable("OutcomeMeasureResults");
                });

            modelBuilder.Entity("PTDoc.Core.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicalRecordNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayerInfoJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId")
                        .HasFilter("ClinicId IS NOT NULL");

                    b.HasIndex("Email")
                        .HasFilter("Email IS NOT NULL");

                    b.HasIndex("LastModifiedUtc");

                    b.HasIndex("MedicalRecordNumber")
                        .IsUnique()
                        .HasFilter("MedicalRecordNumber IS NOT NULL");

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PTDoc.Core.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("IsRevoked", "ExpiresAt");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("PTDoc.Core.Models.StoredRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("IsRevoked");

                    b.HasIndex("Subject");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("StoredRefreshTokens");
                });

            modelBuilder.Entity("PTDoc.Core.Models.SyncConflictArchive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchivedDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ArchivedVersionLastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArchivedVersionModifiedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChosenDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChosenVersionLastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChosenVersionModifiedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("IsResolved");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("SyncConflictArchives");
                });

            modelBuilder.Entity("PTDoc.Core.Models.SyncQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnqueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Operation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnqueuedAt");

                    b.HasIndex("Status");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("SyncQueueItems");
                });

            modelBuilder.Entity("PTDoc.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LicenseExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseState")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId")
                        .HasFilter("ClinicId IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("Email IS NOT NULL");

                    b.HasIndex("IsActive");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PTDoc.Core.Models.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId", "IsArchived");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("PTDoc.Core.Models.UserNotificationPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DoNotDisturb")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InAppNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyAppointmentScheduled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyIncompleteIntake")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyOverdueNote")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyUpcomingAppointment")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SoundAlerts")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("UserNotificationPreferences");
                });

            modelBuilder.Entity("PTDoc.Core.Models.Addendum", b =>
                {
                    b.HasOne("PTDoc.Core.Models.ClinicalNote", "ClinicalNote")
                        .WithMany()
                        .HasForeignKey("ClinicalNoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClinicalNote");
                });

            modelBuilder.Entity("PTDoc.Core.Models.Appointment", b =>
                {
                    b.HasOne("PTDoc.Core.Models.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PTDoc.Core.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PTDoc.Core.Models.ClinicalNote", b =>
                {
                    b.HasOne("PTDoc.Core.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PTDoc.Core.Models.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PTDoc.Core.Models.Patient", "Patient")
                        .WithMany("ClinicalNotes")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Clinic");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PTDoc.Core.Models.ExternalSystemMapping", b =>
                {
                    b.HasOne("PTDoc.Core.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("InternalPatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PTDoc.Core.Models.IntakeForm", b =>
                {
                    b.HasOne("PTDoc.Core.Models.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PTDoc.Core.Models.Patient", "Patient")
                        .WithMany("IntakeForms")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PTDoc.Core.Models.ObjectiveMetric", b =>
                {
                    b.HasOne("PTDoc.Core.Models.ClinicalNote", "Note")
                        .WithMany("ObjectiveMetrics")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("PTDoc.Core.Models.OutcomeMeasureResult", b =>
                {
                    b.HasOne("PTDoc.Core.Models.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PTDoc.Core.Models.ClinicalNote", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PTDoc.Core.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Note");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PTDoc.Core.Models.Patient", b =>
                {
                    b.HasOne("PTDoc.Core.Models.Clinic", "Clinic")
                        .WithMany("Patients")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("PTDoc.Core.Models.Session", b =>
                {
                    b.HasOne("PTDoc.Core.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PTDoc.Core.Models.User", b =>
                {
                    b.HasOne("PTDoc.Core.Models.Clinic", "Clinic")
                        .WithMany("Users")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("PTDoc.Core.Models.UserNotification", b =>
                {
                    b.HasOne("PTDoc.Core.Models.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId");

                    b.HasOne("PTDoc.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PTDoc.Core.Models.UserNotificationPreferences", b =>
                {
                    b.HasOne("PTDoc.Core.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("PTDoc.Core.Models.UserNotificationPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PTDoc.Core.Models.Clinic", b =>
                {
                    b.Navigation("Patients");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PTDoc.Core.Models.ClinicalNote", b =>
                {
                    b.Navigation("ObjectiveMetrics");
                });

            modelBuilder.Entity("PTDoc.Core.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ClinicalNotes");

                    b.Navigation("IntakeForms");
                });

            modelBuilder.Entity("PTDoc.Core.Models.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
