namespace PTDoc.Core.Models;

public static class BodyRegionMap
{
    public static IReadOnlyDictionary<BodyRegion, string> SvgRegionIds { get; } =
        new Dictionary<BodyRegion, string>
        {
            [BodyRegion.AbdomenLeftFront] = "abdomen_left_front",
            [BodyRegion.AbdomenRightFront] = "abdomen_right_front",
            [BodyRegion.ArmLeftBack] = "arm_left_back",
            [BodyRegion.ArmLeftFront] = "arm_left_front",
            [BodyRegion.ArmRightBack] = "arm_right_back",
            [BodyRegion.ArmRightFront] = "arm_right_front",
            [BodyRegion.CalfLeftBack] = "calf_left_back",
            [BodyRegion.CalfLeftFront] = "calf_left_front",
            [BodyRegion.CalfRightBack] = "calf_right_back",
            [BodyRegion.CalfRightFront] = "calf_right_front",
            [BodyRegion.ChestLeftFront] = "chest_left_front",
            [BodyRegion.ChestRightFront] = "chest_right_front",
            [BodyRegion.DeltoidLeftFront] = "deltoid_left_front",
            [BodyRegion.DeltoidRightFront] = "deltoid_right_front",
            [BodyRegion.ElbowLeftBack] = "elbow_left_back",
            [BodyRegion.ElbowLeftFront] = "elbow_left_front",
            [BodyRegion.ElbowRightBack] = "elbow_right_back",
            [BodyRegion.ElbowRightFront] = "elbow_right_front",
            [BodyRegion.FootLeftBack] = "foot_left_back",
            [BodyRegion.FootLeftFront] = "foot_left_front",
            [BodyRegion.FootRightBack] = "foot_right_back",
            [BodyRegion.FootRightFront] = "foot_right_front",
            [BodyRegion.ForearmLeftBack] = "forearm_left_back",
            [BodyRegion.ForearmLeftFront] = "forearm_left_front",
            [BodyRegion.ForearmRightBack] = "forearm_right_back",
            [BodyRegion.ForearmRightFront] = "forearm_right_front",
            [BodyRegion.GlutealLeft] = "gluteal_left",
            [BodyRegion.GlutealRight] = "gluteal_right",
            [BodyRegion.HandLeftBack] = "hand_left_back",
            [BodyRegion.HandLeftPalm] = "hand_left_palm",
            [BodyRegion.HandRightBack] = "hand_right_back",
            [BodyRegion.HandRightPalm] = "hand_right_palm",
            [BodyRegion.HeadBack] = "head_back",
            [BodyRegion.HeadFront] = "head_front",
            [BodyRegion.KneeLeftBack] = "knee_left_back",
            [BodyRegion.KneeLeftFront] = "knee_left_front",
            [BodyRegion.KneeRightBack] = "knee_right_back",
            [BodyRegion.KneeRightFront] = "knee_right_front",
            [BodyRegion.LowerbackLeft] = "lowerback_left",
            [BodyRegion.LowerbackRight] = "lowerback_right",
            [BodyRegion.LowercalfLeftBack] = "lowercalf_left_back",
            [BodyRegion.LowercalfLeftFront] = "lowercalf_left_front",
            [BodyRegion.LowercalfRightBack] = "lowercalf_right_back",
            [BodyRegion.LowercalfRightFront] = "lowercalf_right_front",
            [BodyRegion.MidbackLeft] = "midback_left",
            [BodyRegion.MidbackRight] = "midback_right",
            [BodyRegion.MidtorsoLeftFront] = "midtorso_left_front",
            [BodyRegion.MidtorsoRightFront] = "midtorso_right_front",
            [BodyRegion.NeckBack] = "neck_back",
            [BodyRegion.NeckFront] = "neck_front",
            [BodyRegion.PelvisLeftFront] = "pelvis_left_front",
            [BodyRegion.PelvisRightFront] = "pelvis_right_front",
            [BodyRegion.ShoulderLeftBack] = "shoulder_left_back",
            [BodyRegion.ShoulderLeftFront] = "shoulder_left_front",
            [BodyRegion.ShoulderRightBack] = "shoulder_right_back",
            [BodyRegion.ShoulderRightFront] = "shoulder_right_front",
            [BodyRegion.ThighLeftBack] = "thigh_left_back",
            [BodyRegion.ThighLeftFront] = "thigh_left_front",
            [BodyRegion.ThighRightBack] = "thigh_right_back",
            [BodyRegion.ThighRightFront] = "thigh_right_front",
            [BodyRegion.UpperbackLeft] = "upperback_left",
            [BodyRegion.UpperbackRight] = "upperback_right"
        };

    public static IReadOnlySet<BodyRegion> FrontRegions { get; } = new HashSet<BodyRegion>
    {
        BodyRegion.AbdomenLeftFront,
        BodyRegion.AbdomenRightFront,
        BodyRegion.ArmLeftFront,
        BodyRegion.ArmRightFront,
        BodyRegion.CalfLeftFront,
        BodyRegion.CalfRightFront,
        BodyRegion.ChestLeftFront,
        BodyRegion.ChestRightFront,
        BodyRegion.DeltoidLeftFront,
        BodyRegion.DeltoidRightFront,
        BodyRegion.ElbowLeftFront,
        BodyRegion.ElbowRightFront,
        BodyRegion.FootLeftFront,
        BodyRegion.FootRightFront,
        BodyRegion.ForearmLeftFront,
        BodyRegion.ForearmRightFront,
        BodyRegion.HandLeftPalm,
        BodyRegion.HandRightPalm,
        BodyRegion.HeadFront,
        BodyRegion.KneeLeftFront,
        BodyRegion.KneeRightFront,
        BodyRegion.LowercalfLeftFront,
        BodyRegion.LowercalfRightFront,
        BodyRegion.MidtorsoLeftFront,
        BodyRegion.MidtorsoRightFront,
        BodyRegion.NeckFront,
        BodyRegion.PelvisLeftFront,
        BodyRegion.PelvisRightFront,
        BodyRegion.ShoulderLeftFront,
        BodyRegion.ShoulderRightFront,
        BodyRegion.ThighLeftFront,
        BodyRegion.ThighRightFront
    };

    public static IReadOnlySet<BodyRegion> BackRegions { get; } = new HashSet<BodyRegion>
    {
        BodyRegion.ArmLeftBack,
        BodyRegion.ArmRightBack,
        BodyRegion.CalfLeftBack,
        BodyRegion.CalfRightBack,
        BodyRegion.ElbowLeftBack,
        BodyRegion.ElbowRightBack,
        BodyRegion.FootLeftBack,
        BodyRegion.FootRightBack,
        BodyRegion.ForearmLeftBack,
        BodyRegion.ForearmRightBack,
        BodyRegion.GlutealLeft,
        BodyRegion.GlutealRight,
        BodyRegion.HandLeftBack,
        BodyRegion.HandRightBack,
        BodyRegion.HeadBack,
        BodyRegion.KneeLeftBack,
        BodyRegion.KneeRightBack,
        BodyRegion.LowerbackLeft,
        BodyRegion.LowerbackRight,
        BodyRegion.LowercalfLeftBack,
        BodyRegion.LowercalfRightBack,
        BodyRegion.MidbackLeft,
        BodyRegion.MidbackRight,
        BodyRegion.NeckBack,
        BodyRegion.ShoulderLeftBack,
        BodyRegion.ShoulderRightBack,
        BodyRegion.ThighLeftBack,
        BodyRegion.ThighRightBack,
        BodyRegion.UpperbackLeft,
        BodyRegion.UpperbackRight
    };
}
