using Microsoft.EntityFrameworkCore;using Moq;using PTDoc.Application.Identity;using PTDoc.Application.Insurance;using PTDoc.Core.Models;using PTDoc.Infrastructure.Data;using PTDoc.Infrastructure.Services;
namespace PTDoc.Tests.Insurance;
[Trait("Category","CoreCi")]
public sealed class InsurancePolicyServiceTests:IDisposable
{
    private readonly ApplicationDbContext db;private readonly InsurancePolicyService service;private readonly Guid clinic=Guid.NewGuid();private readonly Patient patient;
    public InsurancePolicyServiceTests(){var tenant=new Mock<ITenantContextAccessor>();tenant.Setup(x=>x.GetCurrentClinicId()).Returns(clinic);var identity=new Mock<IIdentityContextAccessor>();identity.Setup(x=>x.GetCurrentUserId()).Returns(Guid.NewGuid());db=new(new DbContextOptionsBuilder<ApplicationDbContext>().UseInMemoryDatabase($"insurance-{Guid.NewGuid()}").Options,tenant.Object);service=new(db,tenant.Object,identity.Object);patient=new(){Id=Guid.NewGuid(),ClinicId=clinic,FirstName="Patient",LastName="Policy",DateOfBirth=new(1990,1,1)};db.Patients.Add(patient);db.SaveChanges();}
    [Fact]public async Task ActiveCoveragePriority_IsUniquePerPatient(){await service.UpsertPolicyAsync(patient.Id,null,new(){CoveragePriority=InsuranceCoveragePriority.Primary,CarrierDisplayName="Carrier One",PayerType=InsurancePayerType.Commercial},default);await Assert.ThrowsAsync<InvalidOperationException>(()=>service.UpsertPolicyAsync(patient.Id,null,new(){CoveragePriority=InsuranceCoveragePriority.Primary,CarrierDisplayName="Carrier Two",PayerType=InsurancePayerType.Commercial},default));}
    [Fact]public async Task Authorization_IsTypedAndRetainedWithPolicy(){var policy=await service.UpsertPolicyAsync(patient.Id,null,new(){CoveragePriority=InsuranceCoveragePriority.Primary,CarrierDisplayName="Carrier",PayerType=InsurancePayerType.Commercial},default);await service.UpsertAuthorizationAsync(patient.Id,policy.Id,null,new(){AuthorizationType=InsuranceAuthorizationType.Authorization,Status=InsuranceAuthorizationStatus.Approved,AuthorizedUnits=12,UsedUnits=3},default);var result=Assert.Single(await service.ListAsync(patient.Id,default));var authorization=Assert.Single(result.Authorizations);Assert.Equal(12,authorization.AuthorizedUnits);Assert.Equal(3,authorization.UsedUnits);}
    [Fact]public async Task Backfill_IsIdempotent(){patient.PayerInfoJson="""{"insuranceCompanyName":"Example Health","memberIdPolicyNumber":"ABC","authorizationNumber":"AUTH-1","numberOfVisitsOrUnitsAuthorized":"8"}""";await db.SaveChangesAsync();var first=await service.BackfillLegacyPayerDataAsync(default);var second=await service.BackfillLegacyPayerDataAsync(default);Assert.Equal(1,first.PoliciesCreated);Assert.Equal(0,second.PoliciesCreated);Assert.Single(await service.ListAsync(patient.Id,default));}
    [Fact]public async Task PatientDualWrite_ProjectsPolicyAndAuthorizationWithoutErasingExistingValues(){await IntakeDomainProjection.UpsertPatientRecordAsync(db,patient,"""{"insuranceCompanyName":"Example Health","memberIdPolicyNumber":"ABC","authorizationNumber":"AUTH-2","authorizationStatus":"Approved","numberOfVisitsOrUnitsAuthorized":"12"}""",null,null,Guid.NewGuid(),default);await db.SaveChangesAsync();await IntakeDomainProjection.UpsertPatientRecordAsync(db,patient,"""{"insuranceCompanyName":"Example Health","visitsUsed":"4","authorizationReferralHistory":[{"recordType":"Referral","referenceNumber":"REF-1","status":"Approved","startDate":"2026-01-01","endDate":"2026-06-30","visitsOrUnitsAuthorized":"6"}]}""",null,null,Guid.NewGuid(),default);await db.SaveChangesAsync();var policy=Assert.Single(await service.ListAsync(patient.Id,default));Assert.Equal("ABC",policy.MemberOrPolicyNumber);Assert.Equal(2,policy.Authorizations.Count);var authorization=Assert.Single(policy.Authorizations.Where(value=>value.ReferenceNumber=="AUTH-2"));Assert.Equal(12,authorization.AuthorizedUnits);Assert.Equal(4,authorization.UsedUnits);var referral=Assert.Single(policy.Authorizations.Where(value=>value.ReferenceNumber=="REF-1"));Assert.Equal(InsuranceAuthorizationType.Referral,referral.AuthorizationType);}
    public void Dispose()=>db.Dispose();
}
